# Site settings
author: Tam Vu
title: 
header-img: img/home-bg.png
email: vutam_a@hotmail.com
copyright_name: Tam Vu
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  iamtamtamiam

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
